name: Checks

on:
  - push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1.2"

      - name: Build
        run: swift build

      - name: Test
        run: swift test

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup Featurevisor example-1 project
        run: |
          mkdir example-1
          (cd example-1 && npx @featurevisor/cli@2.x init --example=1)
          (cd example-1 && npm install)
          (cd example-1 && npx featurevisor build)
          (cd example-1 && npx featurevisor test)

      - name: Run Featurevisor project tests against Swift SDK
        run: swift run featurevisor test --projectDirectoryPath=./example-1
